### ISSUE TITLE
Compilation error on current master branch

### ISSUE THREAD

**Issue by addap** [kztk-m/sparcl#4]
Hello,

I was trying to compile the current master branch (849f1e5786) but I get an error related to typeclass constraints.
`git bisect master icfp2020_artifact --` tells me that ad7387c8b was the first commit where the compilation starts to fail with this error.

```
$ stack build                                                              [14:55:53]
sparcl-runtime> configure (lib)
sparcl-runtime> Configuring sparcl-runtime-0.1.0.0...
sparcl-runtime> build (lib)
sparcl-runtime> Preprocessing library for sparcl-runtime-0.1.0.0..
sparcl-runtime> Building library for sparcl-runtime-0.1.0.0..
sparcl-runtime> [1 of 2] Compiling Language.Sparcl.Runtime
sparcl-runtime> [2 of 2] Compiling Language.Sparcl.Base
sparcl-runtime>
sparcl-runtime> /home/adrian/japanese/auslandssemester/COLABS/sparcl-master/runtime/src/Language/Sparcl/Base.hs:6:1: warning: [-Wunused-imports]
sparcl-runtime>     The import of ‘Data.Ratio’ is redundant
sparcl-runtime>       except perhaps to import instances from ‘Data.Ratio’
sparcl-runtime>     To import instances alone, use: import Data.Ratio()
sparcl-runtime>   |
sparcl-runtime> 6 | import           Data.Ratio              (Rational)
sparcl-runtime>   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sparcl-runtime>
sparcl-runtime> copy/register
sparcl-runtime> Installing library in /home/adrian/japanese/auslandssemester/COLABS/sparcl-master/.stack-work/install/x86_64-linux-tinfo6/724b0ae458d561e2f1ea59f021a2c82d878c84ed580294aa77eec004812db06d/8.8.4/lib/x86_64-linux-ghc-8.8.4/sparcl-runtime-0.1.0.0-IODh8fJr6GwCPDOGZZF4Qn
sparcl-runtime> Registering library for sparcl-runtime-0.1.0.0..
Building all executables for `sparcl' once. After a successful build of all of them, only specified executables will be rebuilt.
sparcl        > configure (lib + exe)
sparcl        > Configuring sparcl-0.2.0.0...
sparcl        > build (lib + exe)
sparcl        > Preprocessing library for sparcl-0.2.0.0..
sparcl        > Building library for sparcl-0.2.0.0..
sparcl        > [ 1 of 29] Compiling Language.Sparcl.Class
sparcl        > [ 2 of 29] Compiling Language.Sparcl.FreeTyVars
sparcl        > [ 3 of 29] Compiling Language.Sparcl.Pass
sparcl        > [ 4 of 29] Compiling Language.Sparcl.Pretty
sparcl        > [ 5 of 29] Compiling Language.Sparcl.Name
sparcl        > [ 6 of 29] Compiling Language.Sparcl.Multiplicity
sparcl        > [ 7 of 29] Compiling Language.Sparcl.Literal
sparcl        > [ 8 of 29] Compiling Language.Sparcl.Exception
sparcl        > [ 9 of 29] Compiling Language.Sparcl.DebugPrint
sparcl        > [10 of 29] Compiling Language.Sparcl.Command
sparcl        > [11 of 29] Compiling Language.Sparcl.Algorithm.SAT
sparcl        > [12 of 29] Compiling Language.Sparcl.SrcLoc
sparcl        > [13 of 29] Compiling Language.Sparcl.Surface.Parser.Helper
sparcl        > [14 of 29] Compiling Language.Sparcl.Surface.Parser.Id
sparcl        > [15 of 29] Compiling Language.Sparcl.Typing.Type
sparcl        > [16 of 29] Compiling Language.Sparcl.Surface.Syntax
sparcl        > [17 of 29] Compiling Language.Sparcl.Typing.TCMonad
sparcl        > [18 of 29] Compiling Language.Sparcl.Surface.Parser.Exp
sparcl        > [19 of 29] Compiling Language.Sparcl.Surface.Parsing
sparcl        > [20 of 29] Compiling Language.Sparcl.Renaming
sparcl        > [21 of 29] Compiling Language.Sparcl.Core.Syntax
sparcl        > [22 of 29] Compiling Language.Sparcl.Desugar
sparcl        > [23 of 29] Compiling Language.Sparcl.CodeGen.Haskell
sparcl        >
sparcl        > /home/adrian/japanese/auslandssemester/COLABS/sparcl-master/src/Language/Sparcl/CodeGen/Haskell.hs:27:1: warning: [-Wunused-imports]
sparcl        >     The import of ‘Import’
sparcl        >     from module ‘Language.Sparcl.Surface.Syntax’ is redundant
sparcl        >    |
sparcl        > 27 | import           Language.Sparcl.Surface.Syntax as S (Export, Import (..))
sparcl        >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sparcl        > [24 of 29] Compiling Language.Sparcl.Typing.Typing
sparcl        > [25 of 29] Compiling Language.Sparcl.Value
sparcl        >
sparcl        > /home/adrian/japanese/auslandssemester/COLABS/sparcl-master/src/Language/Sparcl/Value.hs:14:1: warning: [-Wunused-imports]
sparcl        >     The import of ‘Control.Monad.Fail’ is redundant
sparcl        >       except perhaps to import instances from ‘Control.Monad.Fail’
sparcl        >     To import instances alone, use: import Control.Monad.Fail()
sparcl        >    |
sparcl        > 14 | import           Control.Monad.Fail
sparcl        >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sparcl        > [26 of 29] Compiling Language.Sparcl.Module
sparcl        > [27 of 29] Compiling Language.Sparcl.TH
sparcl        >
sparcl        > /home/adrian/japanese/auslandssemester/COLABS/sparcl-master/src/Language/Sparcl/TH.hs:71:1: warning: [-Wmissing-signatures]
sparcl        >     Top-level binding with no type signature:
sparcl        >       plainTV :: TH.Name -> TH.TyVarBndr
sparcl        >    |
sparcl        > 71 | plainTV =
sparcl        >    | ^^^^^^^
sparcl        >
sparcl        > /home/adrian/japanese/auslandssemester/COLABS/sparcl-master/src/Language/Sparcl/TH.hs:78:1: warning: [-Wmissing-signatures]
sparcl        >     Top-level binding with no type signature:
sparcl        >       plainTVSpecific :: TH.Name -> TH.TyVarBndr
sparcl        >    |
sparcl        > 78 | plainTVSpecific =
sparcl        >    | ^^^^^^^^^^^^^^^
sparcl        > [28 of 29] Compiling Language.Sparcl.Eval
sparcl        > [29 of 29] Compiling Language.Sparcl.REPL
sparcl        >
sparcl        > /home/adrian/japanese/auslandssemester/COLABS/sparcl-master/src/Language/Sparcl/REPL.hs:80:10: error:
sparcl        >     • Could not deduce (MonadThrow m)
sparcl        >         arising from the superclasses of an instance declaration
sparcl        >       from the context: HL.MonadException m
sparcl        >         bound by the instance declaration
sparcl        >         at src/Language/Sparcl/REPL.hs:80:10-55
sparcl        >       Possible fix:
sparcl        >         add (MonadThrow m) to the context of the instance declaration
sparcl        >     • In the instance declaration for ‘MonadCatch (MyInputT m)’
sparcl        >    |
sparcl        > 80 | instance HL.MonadException m => MonadCatch (MyInputT m) where
sparcl        >    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sparcl        >
Completed 2 action(s).

--  While building package sparcl-0.2.0.0 (scroll up to its section to see the error) using:
      /home/adrian/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.4 --verbose=1 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0 build lib:sparcl exe:sparcl-exe --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

My stack version is the following (installed via ghcup)
```
Version 2.9.1, Git revision 409d56031b4240221d656db09b2ba476fe6bb5b1 x86_64 hpack-0.35.0
```

**Comment by kztk-m** [comment]
Thank you for letting me know the issue. Now, the commit https://github.com/kztk-m/sparcl/commit/1ac8a8b324aab2f0c701c071167c4ce40e100947 attempts to fix this. 

I here wrote "attempts to fix" as I am currently working on M1 Mac, for which ghc 8.8.4 (associated with lts-16.12) is not available. So, @addap could you try the latest version to check if the issue is resolved?

**Comment by addap** [comment]
Ok thank you, yes now it is compiling.
